import streamlit as st
import requests
import pdfkit
import tempfile
import os
import json

st.set_page_config(page_title="Mini SEO Auditor", layout="centered")
st.title("🚀 Mini SEO Auditor - Google PageSpeed API")

# Input field for the URL
site_url = st.text_input("Enter the website URL to audit:", placeholder="https://example.com")

# Function to fetch data from Google PageSpeed API
def fetch_lighthouse_data(site_url):
    api_url = f"https://www.googleapis.com/pagespeedonline/v5/runPagespeed?url={site_url}&category=performance&category=seo&strategy=mobile"
    try:
        response = requests.get(api_url)
        response.raise_for_status()
        data = response.json()
        seo_score = data['lighthouseResult']['categories']['seo']['score'] * 100
        perf_score = data['lighthouseResult']['categories']['performance']['score'] * 100
        title = data['lighthouseResult']['finalUrl']

        return {
            'title': title,
            'seo_score': seo_score,
            'perf_score': perf_score
        }, data
    except Exception as e:
        st.error(f"Failed to fetch audit data: {e}")
        return None, None

# Function to generate PDF report using pdfkit
def generate_pdf_report(data):
    html = f"""
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; padding: 20px; }}
            h1 {{ color: #4CAF50; }}
            .section {{ margin-bottom: 20px; }}
        </style>
    </head>
    <body>
        <h1>SEO Audit Report</h1>
        <div class='section'><strong>URL:</strong> {data['title']}</div>
        <div class='section'><strong>SEO Score:</strong> {data['seo_score']}%</div>
        <div class='section'><strong>Performance Score:</strong> {data['perf_score']}%</div>
        <p>Audit generated by Mini SEO Auditor using Google PageSpeed API.</p>
    </body>
    </html>
    """
    with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp_pdf:
        pdfkit.from_string(html, tmp_pdf.name)
        return tmp_pdf.name

# Main logic
if site_url:
    if st.button("Run Audit"):
        with st.spinner("Fetching audit data..."):
            summary_data, full_json = fetch_lighthouse_data(site_url)
            if summary_data:
                st.success("Audit completed!")
                st.write("### Summary:")
                st.write(f"**URL**: {summary_data['title']}")
                st.write(f"**SEO Score**: {summary_data['seo_score']}%")
                st.write(f"**Performance Score**: {summary_data['perf_score']}%")

                # Generate and offer PDF download
                pdf_path = generate_pdf_report(summary_data)
                with open(pdf_path, "rb") as f:
                    st.download_button("📥 Download PDF Report", f, file_name="seo_audit_report.pdf", mime="application/pdf")

                # Optional: Offer JSON download
                json_path = tempfile.NamedTemporaryFile(delete=False, suffix=".json")
                with open(json_path.name, "w") as jf:
                    json.dump(full_json, jf)
                with open(json_path.name, "rb") as jf:
                    st.download_button("📄 Download Full JSON Report", jf, file_name="raw_lighthouse_report.json", mime="application/json")